[package]
name = "ndata"
version = "0.2.16"
edition = "2021"
license = "MIT"
readme = "README.md"
description = "A self-owned data structure with an internal heap and garbage collection."
homepage = "https://github.com/mraiser/ndata"
documentation = "https://docs.rs/ndata/latest/ndata/"
repository = "https://github.com/mraiser/ndata"

[features]
serde_support = ["serde_json"]
debug_mutex = ["backtrace"]
reload = []

[dependencies]
serde_json = { version = "1.0.83", optional = true }
backtrace = { version = "0.3.66", optional = true }

[lib]
name = "ndata"
path = "src/ndata.rs"

