[package]
name = "ndata"
version = "0.1.2"
edition = "2021"
license = "MIT"
readme = "README.md"
description = "A self-owned data structure with an internal heap and garbage collection."
homepage = "https://github.com/mraiser/ndata"
documentation = "https://docs.rs/ndata/latest/ndata/"
repository = "https://github.com/mraiser/ndata"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
state="0.5.2"

[lib]
name = "ndata"
path = "src/ndata.rs"

